project:
  type: book
  output-dir: docs
  
book:
  title: "Essay of my research Journey"
  author: "Jaeseok Hwang"
  site-url: https://jaeseokh.github.io/essays/
  repo-url: https://https://github.com/jaeseokh/essay_of_research/
  repo-branch: master
  repo-actions: [edit]
  sharing: [facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - text: "---"
    - part: " Statistical Analysis in Application to Economics Models"
      chapters: 
        - E01-Basic Crop Production Model.qmd
        - E02-Estimation of Yield Response.qmd
        - E03-Spatial and Time Series.qmd
        - E04-Bayesian Quantile Regression.qmd
    - text: "---"
    - part: "Essay of Price Analysis"
      chapters: 
        - P01-price_movement.qmd
        - P02-stock_money_ag.qmd
    - text: "---"
    - part: "Essay of Statistical Learning(AI)"
      chapters: 
        - S01-what-is-learning.qmd
        - S02-how-to-use-learning.qmd
  appendices:
    - A01-appendix.qmd
    

bibliography: myref.bib

format:
  html: 
    include-in-header:
      - analytics.html
    theme: cosmo
    code-link: true
    callout-icon: false
    fig-align: center
    code-tools: true

execute:
  warning: false
  message: false
  fig-align: center